version: "3"
services: 
    react:
        build:
            context: .
            dockerfile: "Dockerfile"
        ports: 
            - "3000:80"
        volumes:
            - ".:/app"
            - "/app/node_modules"
        stdin_open: true